packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.0-beta.9
  '@better-auth/expo': 1.4.0-beta.9
  '@eslint/js': ^9.38.0
  '@playwright/test': ^1.50.1
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.23.8
  '@tanstack/react-query': ^5.90.8
  '@trpc/client': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/node': ^22.10.0
  '@vitejs/plugin-react': ^4.3.4
  '@vitest/ui': ^3.0.5
  better-auth: 1.4.0-beta.9
  eslint: ^9.18.0
  prettier: ^3.4.2
  tailwindcss: ^4.0.0
  typescript: ^5.7.3
  vite: 7.1.12
  vitest: ^3.0.5
  zod: 3.25.76

catalogs:
  react19:
    '@types/react': ~19.1.0
    '@types/react-dom': ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
